apiVersion: v1
kind: Service
metadata:
  name: flask-test-service-2cc
spec:
  selector:
    app: flask-test-app-2cc
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-test-app-2cc
spec:
  selector:
    matchLabels:
      app: flask-test-app-2cc
  replicas: 3
  template:
    metadata:
      labels:
        app: flask-test-app-2cc
    spec:
      containers:
      - name: flask-test-app-2cc
        image: flask-kubernetes
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
