apiVersion: v1
kind: Service
metadata:
  name: fs
spec:
  selector:
    app: fa
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fd
spec:
  selector:
    matchLabels:
      app: fa
  replicas: 4
  template:
    metadata:
      labels:
        app: fa
    spec:
      containers:
      - name: fa
        image: mylogin
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
          - name: SECRET_EMAIL
            valueFrom:
              secretKeyRef:
                name: flask-secret
                key: email
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: flask-secret
                key: password
