apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeploy
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 3
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: appdeploy
          image: appdocker
          imagePullPolicy: Never
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: appdeploy
  labels:
    app: flask
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      name: flask

  selector:
    app: flask
      
