apiVersion: v1
kind: Service
metadata:
  name: reg-service
spec:
  selector:
    app: reg-app
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reg-app
spec:
  selector:
    matchLabels:
      app: reg-app
  replicas: 3
  template:
    metadata:
      labels:
        app: reg-app
    spec:
      imagePullSecrets:
      - name: registrypullsecret
      containers:
      - name: reg-app
        image: docker-registry-a:5000/hi/k8app:v1
        ports:
        - containerPort: 5000
        imagePullPolicy: IfNotPresent
