apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJjb2RlLnFidXJzdC5jb206NDU2NyI6IHsKCQkJImF1dGgiOiAiWVhOM2FXNHViWFZzYkdGamFHVnllVHB4WW5WeWMzUkFNVEl6IgoJCX0sCgkJInFiZHItaW50ZXJuYWwuY29tIjogewoJCQkiYXV0aCI6ICJjV0prY2pweFltUnkiCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson
