apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: ng
  replicas: 1
  template:
    metadata:
      labels:
        app: ng
    spec:
      containers:
      - name: ngc
        image: nginx
